export const SET_TIME = "SET_TIME"
export const SET_START_TIME = "SET_START_TIME"
export const SET_END_TIME = "SET_END_TIME"
export const SET_IS_PAUSE = "SET_IS_PAUSE"
export const SET_NAME = "SET_NAME"
export const SET_ID = "SET_ID"
export const SET_TIMEOUT = "SET_TIMEOUT"